---

- name: install python-pip
  package:
    name: python-pip
    state: present
  when: ansible_python_version is version('3', '<')

- name: install python3-pip
  package:
    name: python3-pip
    state: present
  when: ansible_python_version is version('3', '>=')
