---

- name: Install python-pip
  ansible.builtin.package:
    name: python-pip
    state: present
  when: ansible_python_version is version('3', '<')

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present
  when: ansible_python_version is version('3', '>=')
