---
- name: Adding apt key
  block:
    - name: Try to get apt key via keyserver (this fails sometimes)
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ docker_ce_apt_key_id }}"
        state: present
  rescue:
    - name: Falling back and use url of key
      ansible.builtin.apt_key:
        url: "{{ docker_ce_apt_key_fallback_url }}"
        id: "{{ docker_ce_apt_key_id }}"
        state: present

- name: Install python-apt
  ansible.builtin.package:
    name: python-apt
    state: present
  when: ansible_python_version is version('3', '<')

- name: Install python3-apt
  ansible.builtin.package:
    name: python3-apt
    state: present
  when: ansible_python_version is version('3', '>=')

# TODO: set arch - currently only amd64/x86_64 is supported
- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64]
      {{ docker_ce_apt_base_url }}{{ ansible_distribution | lower }}
      {{ ansible_distribution_release | lower }} stable"
    state: present
    update_cache: true
